settings:
  APP_DISPLAY_NAME: Сетка Matrix
  PRODUCTION_APP_NAME: Сетка Matrix
  APP_GROUP_IDENTIFIER: group.com.setkamatrix.ios
  BASE_BUNDLE_IDENTIFIER: com.setkamatrix.ios
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: "JTPUAFFZZQ"

  # Optional configuration to load accounts from Element Classic.
  CLASSIC_APP_GROUP_IDENTIFIER: group.com.setkamatrix.ios.classic
  CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: com.setkamatrix.ios.encryption-manager-service
  CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: "$(DEVELOPMENT_TEAM).com.setkamatrix.ios.keychain.shared"
